owner: sonixapp
repo: sonixapp.github.io

sites:
  - name: api.sonixapp.com
    method: POST
    url: https://api.sonixapp.com/graphql
    headers:
      - "Content-Type: application/json"
    body: '{"query":"{__typename}"}'
  - name: join.sonixapp.com
    url: https://join.sonixapp.com
  - name: sonixapp.com
    url: https://sonixapp.com
  - name: test
    url: https://sonixapp.com/testtesttest

status-website:
  cname: sonixapp.github.io
  theme: light
  logoUrl: https://raw.githubusercontent.com/sonixapp/sonixapp.github.io/master/assets/sonix.jpeg
  name: Sonix
  introTitle: "SONIX is a voice chat that keeps things simple and straight to the point."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: Sonix
      href: https://sonixapp.com
i18n:
  footer: Powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
