owner: sonixapp
repo: sonixapp.github.io

sites:
  - name: API
    url: https://api.sonixapp.com/health
  - name: Join
    url: https://join.sonixapp.com
  - name: Website
    url: https://sonixapp.com

status-website:
  cname: sonixapp.github.io
  theme: light
  logoUrl: https://raw.githubusercontent.com/sonixapp/sonixapp.github.io/master/assets/sonix.jpeg
  name: Sonix
  introTitle: "SONIX is a voice chat that keeps things simple and straight to the point."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: Sonix
      href: https://sonixapp.com
i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
