# Change these first
owner: sonixapp # Your GitHub organization or username, where this repository lives
repo: sonixapp.github.io # The name of this repository

sites:
  - name: API
    url: https://api.sonixapp.com/readyz
  - name: Join
    url: https://join.sonixapp.com
  - name: Website
    url: https://sonixapp.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: sonixapp.github.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sonix
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: Sonix
      href: https://sonixapp.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
